// Package oui embeds the IEEE MA-L, MA-M and MA-S registries as a gzipped
// TSV (prefix hex, tab, organisation name), generated by `make oui`
// (data/oui/gen) and regenerated each release. internal/identify parses it.
package oui

import _ "embed"

// Data is oui.tsv.gz.
//
//go:embed oui.tsv.gz
var Data []byte
